openapi: 3.0.3
info:
  title: OTPless Authentication API
  description: API for initiating OAuth authentication using OTPless.
  version: 1.0.0
servers:
  - url: https://auth.otpless.app
    description: Production server
paths:
  /auth/v1/initiate/oauth:
    post:
      summary: Initiate OAuth
      description: >
        This endpoint initiates an WhatsApp OAuth authentication flow using the
        specified channel.
      operationId: initiateOauth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - channel
                - redirectURI
              type: object
              properties:
                channel:
                  type: string
                  example: WHATSAPP
                  description: The channel through which the OAuth link will be sent.
                redirectURI:
                  type: string
                  example: your://redirecturi
                  description: >-
                    The URI to which the user will be redirected after
                    authentication.
      responses:
        '200':
          description: OAuth link generated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    example: unique_request_id
                    description: The unique identifier for the WhatsApp OAuth request.
                  link:
                    type: string
                    example: https://otpless.me/0EpixHJ02inMw2f
                    description: The WhatsApp OAuth link generated for authentication.
        '400':
          description: Bad request. Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid Request
                    description: A brief description of the error.
                  errorCode:
                    type: string
                    example: Error Code
                    description: A specific code representing the error type.
                  description:
                    type: string
                    example: Error Code description
                    description: Detailed description of the error.
        '401':
          description: Unauthorized. Access blocked.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Access blocked
                    description: A brief description of the error.
                  description:
                    type: string
                    example: Error Description
                    description: Detailed description of the error.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Something went wrong. Please try again!
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: clientId
    ApiSecretAuth:
      type: apiKey
      in: header
      name: clientSecret
security:
  - ApiKeyAuth: []
    ApiSecretAuth: []
